name = "test"
main = "worker.js"
compatibility_date = "2023-10-01"

# Environment Variables (GitHub Secrets ကနေ ဖြည့်မှာမို့ ဒီမှာ အလွတ်ထားပါ)
[vars]
R2_ACCOUNT_ID = ""
R2_BUCKET_NAME = ""
# Access Key တွေကို လုံခြုံရေးအရ ဒီဖိုင်ထဲ မရေးရပါ
